networks:
  infra-db:
    external: true
  redis:
    external: true
x-typebot-env:
  HOSTNAME: 0.0.0.0
  DATABASE_URL: 'postgresql://${SERVICE_USER_POSTGRESQL}:${SERVICE_PASSWORD_POSTGRESQL}@postgresql:5432/${POSTGRES_DB:-typebot}'
  ENCRYPTION_SECRET: '${SERVICE_BASE64_32_SECRET}'
  NEXTAUTH_URL: '${SERVICE_FQDN_BUILDER}'
  NEXT_PUBLIC_VIEWER_URL: '${SERVICE_FQDN_VIEWER}'
  ADMIN_EMAIL: '${ADMIN_EMAIL:-admin@example.com}'
  DEFAULT_WORKSPACE_PLAN: UNLIMITED
  NEXTAUTH_URL_INTERNAL: 'http://localhost:3000'
  DISABLE_SIGNUP: '${DISABLE_SIGNUP:-true}'
  REDIS_PASSWORD: "${REDIS_PASSWORD:-''}"
  REDIS_URL: 'redis://:${REDIS_PASSWORD}@redis:6379/1'
  SMTP_USERNAME: "${SMTP_USERNAME:-''}"
  SMTP_PASSWORD: "${SMTP_PASSWORD:-''}"
  SMTP_HOST: '${SMTP_HOST:-maildev}'
  SMTP_PORT: '${SMTP_PORT:-1025}'
  NEXT_PUBLIC_SMTP_FROM: '${NEXT_PUBLIC_SMTP_FROM:-admin@example.com}'
  SMTP_SECURE: '${SMTP_SECURE:-true}'
  SMTP_IGNORE_TLS: '${SMTP_IGNORE_TLS:-true}'
  SMTP_AUTH_DISABLED: '${SMTP_AUTH_DISABLED:-false}'
  DEBUG: '${DEBUG:-true}'
  NEXT_PUBLIC_UNSPLASH_APP_NAME: '${UNSPLASH_APP_NAME:-Typebot}'
  NEXT_PUBLIC_UNSPLASH_ACCESS_KEY: '${UNSPLASH_ACCESS_KEY:-YOUR_UNSPLASH_ACCESS_KEY}'
  NEXT_PUBLIC_PEXELS_API_KEY: '${PEXELS_API_KEY:-YOUR_PEXELS_API_KEY}'
services:
  builder:
    image: 'baptistearno/typebot-builder:latest'
    networks:
      - infra-db
      - redis
    environment:
      HOSTNAME: 0.0.0.0
      SERVICE_FQDN_BUILDER: ''
      DATABASE_URL: 'postgresql://${SERVICE_USER_POSTGRESQL}:${SERVICE_PASSWORD_POSTGRESQL}@postgresql:5432/${POSTGRES_DB:-typebot}'
      ENCRYPTION_SECRET: '${SERVICE_BASE64_32_SECRET}'
      NEXTAUTH_URL: '${SERVICE_FQDN_BUILDER}'
      NEXT_PUBLIC_VIEWER_URL: '${SERVICE_FQDN_VIEWER}'
      ADMIN_EMAIL: '${ADMIN_EMAIL:-admin@example.com}'
      DEFAULT_WORKSPACE_PLAN: UNLIMITED
      NEXTAUTH_URL_INTERNAL: 'http://localhost:3000'
      DISABLE_SIGNUP: '${DISABLE_SIGNUP:-true}'
      REDIS_PASSWORD: "${REDIS_PASSWORD:-''}"
      REDIS_URL: 'redis://:${REDIS_PASSWORD}@redis:6379/1'
      SMTP_USERNAME: "${SMTP_USERNAME:-''}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:-''}"
      SMTP_HOST: '${SMTP_HOST:-maildev}'
      SMTP_PORT: '${SMTP_PORT:-1025}'
      NEXT_PUBLIC_SMTP_FROM: '${NEXT_PUBLIC_SMTP_FROM:-admin@example.com}'
      SMTP_SECURE: '${SMTP_SECURE:-true}'
      SMTP_IGNORE_TLS: '${SMTP_IGNORE_TLS:-true}'
      SMTP_AUTH_DISABLED: '${SMTP_AUTH_DISABLED:-false}'
      DEBUG: '${DEBUG:-true}'
      NEXT_PUBLIC_UNSPLASH_APP_NAME: '${UNSPLASH_APP_NAME:-Typebot}'
      NEXT_PUBLIC_UNSPLASH_ACCESS_KEY: '${UNSPLASH_ACCESS_KEY:-YOUR_UNSPLASH_ACCESS_KEY}'
      NEXT_PUBLIC_PEXELS_API_KEY: '${PEXELS_API_KEY:-YOUR_PEXELS_API_KEY}'
  viewer:
    image: 'baptistearno/typebot-viewer:latest'
    networks:
      - infra-db
      - redis
    environment:
      HOSTNAME: 0.0.0.0
      SERVICE_FQDN_VIEWER: ''
      DATABASE_URL: 'postgresql://${SERVICE_USER_POSTGRESQL}:${SERVICE_PASSWORD_POSTGRESQL}@postgresql:5432/${POSTGRES_DB:-typebot}'
      ENCRYPTION_SECRET: '${SERVICE_BASE64_32_SECRET}'
      NEXTAUTH_URL: '${SERVICE_FQDN_BUILDER}'
      NEXT_PUBLIC_VIEWER_URL: '${SERVICE_FQDN_VIEWER}'
      ADMIN_EMAIL: '${ADMIN_EMAIL:-admin@example.com}'
      DEFAULT_WORKSPACE_PLAN: UNLIMITED
      NEXTAUTH_URL_INTERNAL: 'http://localhost:3000'
      DISABLE_SIGNUP: '${DISABLE_SIGNUP:-true}'
      REDIS_PASSWORD: "${REDIS_PASSWORD:-''}"
      REDIS_URL: 'redis://:${REDIS_PASSWORD}@redis:6379/1'
      SMTP_USERNAME: "${SMTP_USERNAME:-''}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:-''}"
      SMTP_HOST: '${SMTP_HOST:-maildev}'
      SMTP_PORT: '${SMTP_PORT:-1025}'
      NEXT_PUBLIC_SMTP_FROM: '${NEXT_PUBLIC_SMTP_FROM:-admin@example.com}'
      SMTP_SECURE: '${SMTP_SECURE:-false}'
      SMTP_IGNORE_TLS: '${SMTP_IGNORE_TLS:-true}'
      SMTP_AUTH_DISABLED: '${SMTP_AUTH_DISABLED:-false}'
      DEBUG: '${DEBUG:-true}'
      NEXT_PUBLIC_UNSPLASH_APP_NAME: '${UNSPLASH_APP_NAME:-Typebot}'
      NEXT_PUBLIC_UNSPLASH_ACCESS_KEY: '${UNSPLASH_ACCESS_KEY:-YOUR_UNSPLASH_ACCESS_KEY}'
      NEXT_PUBLIC_PEXELS_API_KEY: '${PEXELS_API_KEY:-YOUR_PEXELS_API_KEY}'
